// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tempizhere/vaultfactory/internal/shared/interfaces (interfaces: DataRepository,VersionRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	models "github.com/tempizhere/vaultfactory/internal/shared/models"
)

// MockDataRepository is a mock of DataRepository interface.
type MockDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDataRepositoryMockRecorder
}

// MockDataRepositoryMockRecorder is the mock recorder for MockDataRepository.
type MockDataRepositoryMockRecorder struct {
	mock *MockDataRepository
}

// NewMockDataRepository creates a new mock instance.
func NewMockDataRepository(ctrl *gomock.Controller) *MockDataRepository {
	mock := &MockDataRepository{ctrl: ctrl}
	mock.recorder = &MockDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataRepository) EXPECT() *MockDataRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataRepository) Create(arg0 context.Context, arg1 *models.DataItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDataRepository) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataRepository)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockDataRepository) GetByID(arg0 context.Context, arg1 uuid.UUID) (*models.DataItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*models.DataItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDataRepositoryMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDataRepository)(nil).GetByID), arg0, arg1)
}

// GetByUserID mocks base method.
func (m *MockDataRepository) GetByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*models.DataItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*models.DataItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDataRepositoryMockRecorder) GetByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDataRepository)(nil).GetByUserID), arg0, arg1)
}

// GetByUserIDAndType mocks base method.
func (m *MockDataRepository) GetByUserIDAndType(arg0 context.Context, arg1 uuid.UUID, arg2 models.DataType) ([]*models.DataItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndType", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.DataItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDAndType indicates an expected call of GetByUserIDAndType.
func (mr *MockDataRepositoryMockRecorder) GetByUserIDAndType(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndType", reflect.TypeOf((*MockDataRepository)(nil).GetByUserIDAndType), arg0, arg1, arg2)
}

// GetUpdatedSince mocks base method.
func (m *MockDataRepository) GetUpdatedSince(arg0 context.Context, arg1 uuid.UUID, arg2 time.Time) ([]*models.DataItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatedSince", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*models.DataItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpdatedSince indicates an expected call of GetUpdatedSince.
func (mr *MockDataRepositoryMockRecorder) GetUpdatedSince(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatedSince", reflect.TypeOf((*MockDataRepository)(nil).GetUpdatedSince), arg0, arg1, arg2)
}

// Update mocks base method.
func (m *MockDataRepository) Update(arg0 context.Context, arg1 *models.DataItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDataRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDataRepository)(nil).Update), arg0, arg1)
}

// MockVersionRepository is a mock of VersionRepository interface.
type MockVersionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVersionRepositoryMockRecorder
}

// MockVersionRepositoryMockRecorder is the mock recorder for MockVersionRepository.
type MockVersionRepositoryMockRecorder struct {
	mock *MockVersionRepository
}

// NewMockVersionRepository creates a new mock instance.
func NewMockVersionRepository(ctrl *gomock.Controller) *MockVersionRepository {
	mock := &MockVersionRepository{ctrl: ctrl}
	mock.recorder = &MockVersionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionRepository) EXPECT() *MockVersionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVersionRepository) Create(arg0 context.Context, arg1 *models.DataVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVersionRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVersionRepository)(nil).Create), arg0, arg1)
}

// GetByDataID mocks base method.
func (m *MockVersionRepository) GetByDataID(arg0 context.Context, arg1 uuid.UUID) ([]*models.DataVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDataID", arg0, arg1)
	ret0, _ := ret[0].([]*models.DataVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDataID indicates an expected call of GetByDataID.
func (mr *MockVersionRepositoryMockRecorder) GetByDataID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDataID", reflect.TypeOf((*MockVersionRepository)(nil).GetByDataID), arg0, arg1)
}

// GetLatestVersion mocks base method.
func (m *MockVersionRepository) GetLatestVersion(arg0 context.Context, arg1 uuid.UUID) (*models.DataVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersion", arg0, arg1)
	ret0, _ := ret[0].(*models.DataVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersion indicates an expected call of GetLatestVersion.
func (mr *MockVersionRepositoryMockRecorder) GetLatestVersion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersion", reflect.TypeOf((*MockVersionRepository)(nil).GetLatestVersion), arg0, arg1)
}

